on: [push, pull_request]
name: Test
jobs:
  test:
    strategy:
      matrix:
        go-version: [1.16.x, 1.17.x]
    runs-on: ubuntu-latest
    steps:
    - name: Install Go
      uses: actions/setup-go@v2
      with:
        go-version: ${{ matrix.go-version }}
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Build package
      run: go build ./pkg
    - name: Lint
      uses: golangci/golangci-lint-action@v2
      with:
        version: v1.45.2
    - name: Test
      run: go test ./...
    - name: Build example executable
      run: go build ./cmd/rpmdb
